version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "9592:9592"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "transactionsdb"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: